// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCwWN1QY6NGQXkAi0KtI4sxisZ8R8AqVQ',
    appId: '1:266647224416:web:089e9a133a8e6ed7c94305',
    messagingSenderId: '266647224416',
    projectId: 'teacher-attendance-a108c',
    authDomain: 'teacher-attendance-a108c.firebaseapp.com',
    storageBucket: 'teacher-attendance-a108c.firebasestorage.app',
    measurementId: 'G-C7620ZCSV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnu8-8Y7DdLNqeajdn0Flad83s9GsTcmU',
    appId: '1:266647224416:android:8ca5560d4160c5aec94305',
    messagingSenderId: '266647224416',
    projectId: 'teacher-attendance-a108c',
    storageBucket: 'teacher-attendance-a108c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEGZ77aYEy0oajkXFST5UCjzjZoeqS_Cg',
    appId: '1:266647224416:ios:ffb3dcbbbb7603aec94305',
    messagingSenderId: '266647224416',
    projectId: 'teacher-attendance-a108c',
    storageBucket: 'teacher-attendance-a108c.firebasestorage.app',
    iosBundleId: 'com.example.teacherAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEGZ77aYEy0oajkXFST5UCjzjZoeqS_Cg',
    appId: '1:266647224416:ios:ffb3dcbbbb7603aec94305',
    messagingSenderId: '266647224416',
    projectId: 'teacher-attendance-a108c',
    storageBucket: 'teacher-attendance-a108c.firebasestorage.app',
    iosBundleId: 'com.example.teacherAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCwWN1QY6NGQXkAi0KtI4sxisZ8R8AqVQ',
    appId: '1:266647224416:web:e06946a5bc8e29a2c94305',
    messagingSenderId: '266647224416',
    projectId: 'teacher-attendance-a108c',
    authDomain: 'teacher-attendance-a108c.firebaseapp.com',
    storageBucket: 'teacher-attendance-a108c.firebasestorage.app',
    measurementId: 'G-2C84J4JEQC',
  );
}
