import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Firebase core package
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'profile_page.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'attendance_screen.dart';


// Main entry point of the Flutter app
void main() async {
  // Ensures that all bindings and services are initialized before runApp()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase before the app runs
  // firebase_options.dart contains config from your google-services.json
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Load saved teacher info
  SharedPreferences prefs = await SharedPreferences.getInstance();
  String? name = prefs.getString('teacherName');
  String? phone = prefs.getString('teacherPhone');

  

  // Decide initial screen based on saved login info
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    home: (name != null && phone != null)
        ? AttendanceScreen(teacherName: name, phoneNumber: phone)
        : const ProfilePage(),
  ));
}

// Root widget of the app
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Teacher Attendance',
      debugShowCheckedModeBanner: false, // Removes debug banner
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const ProfilePage(),
    );
  }
}

// Stateful widget for the Home Screen
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

// State class for Home Screen
class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    // Later: Here we can check if teacher profile exists in Firestore
    // If not, navigate to Profile Setup Screen
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: const Center(child: Text('Welcome! Firebase is now connected.')),
    );
  }


}
